version: "3.8"


services:
  web:
    build: .
    container_name: "web"
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    command: mongod --noauth
    env_file:
      - .env
    volumes:
      - mongo:/data/db
    ports:
      - "6000:27017"
    restart: always

volumes:
  mongo: