version: "3.8"


services:
  web:
    build: .
    container_name: "web"
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always