version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  web:
    build: .
    container_name: "web"
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - app-tier
    depends_on:
      - kafka
      - zookeeper

  mongo:
    image: mongo:latest
    container_name: mongo
    command: mongod --noauth
    env_file:
      - .env
    volumes:
      - mongo:/data/db
    ports:
      - "6000:27017"
    restart: always
    networks:
      - app-tier

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    env_file:
      - .env
    networks:
      - app-tier

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    env_file:
      - .env
    networks:
      - app-tier

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - '8081:8080'
    depends_on:
      - kafka
      - zookeeper
    env_file:
      - .env
    networks:
      - app-tier

  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - "6379:6379"
    depends_on:
      - web
    networks:
      - app-tier



volumes:
  mongo:
